# Generated by Django 4.2.1 on 2023-05-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0003_remove_paiement_paiement_date_paiement_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
