# Generated by Django 4.2.1 on 2023-05-27 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0004_alter_paiement_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
