# Generated by Django 4.2.1 on 2023-05-31 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0005_alter_paiement_due_date_alter_paiement_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='user',
        ),
    ]
