# Generated by Django 4.2.1 on 2023-05-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodybuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodybuilder',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
