# Generated by Django 4.2.1 on 2023-05-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodybuilder', '0002_bodybuilder_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodybuilder',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bodybuilder',
            name='phone',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
