# Generated by Django 4.2.1 on 2023-06-03 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodybuilder', '0003_alter_bodybuilder_full_name_alter_bodybuilder_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodybuilder',
            name='join_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
