# Generated by Django 4.2.1 on 2023-06-03 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodybuilder', '0004_alter_bodybuilder_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodybuilder',
            name='join_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
